### PR TITLE
CRAN ready

### PR DESCRIPTION
**Pull request by dokato**
This pull request solves problems mentioned by `R CMD check` like missing imports, undocumented objects etc. Moreover, `man/` folder with roxygen generated documentation added.

### CODE REVIEW

**Comment by filipstachura** [comment]
Why do you remove package specification from function calls?

**Comment by dokato** [comment]
Because when we use only one function from the package (like `tibble`), I think there is no need to import all the others and use direct call.

**Comment by filipstachura** [comment]
PTAL: Imports section of http://r-pkgs.had.co.nz/namespace.html 
Please ask @marekrogala for final decision and let me know.

```
Unless there is a strong reason not to, it’s better to be explicit. It’s a little more work to write, but a lot easier to read when you come back to the code in the future. The converse is not true.
```

**Comment by dokato** [comment]
@filipstachura My second impression is that you are right. Changed.

**Comment by marekrogala** [comment]
LGTM, R CMD check passes

```
R CMD check results
0 errors | 0 warnings | 2 notes

R CMD check succeeded
```

**Pull request merged**
